# Gradient를 구하는 방법

### element wise 곱셈

In [2]:
import torch

In [3]:
A = torch.ones(5, 3, 3)
print(A.shape)

v = torch.arange(0, 5)
print(v.shape)

torch.Size([5, 3, 3])
torch.Size([5])


In [5]:
v_tensor = v.view(v.size()[0], 1, 1)
print(v_tensor.shape)

torch.Size([5, 1, 1])


In [8]:
result = v_tensor*A
result

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])

### gather 기능

In [9]:
"""torch.gather()"""
A = torch.arange(1, 10)
indices = torch.tensor([0, 3, 5, 6])
print(torch.gather(A, 0, indices))

tensor([1, 4, 6, 7])


In [10]:
A = torch.arange(25).reshape(5,5)
indices = torch.tensor([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3],
    [3, 4, 1],
    [0, 0, 0]
])

print(torch.gather(A, 1, indices))

tensor([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 13],
        [18, 19, 16],
        [20, 20, 20]])


### expand와 repeat 기능
- torch에서 값을 반복시키는 대표적인 연산자
- 먼저 expand는 특정 텐서를 반복하여 생성하며 개수가 1인 차원에만 적용하여 반복할 수 있다.

In [12]:
"""expand"""
x = torch.tensor([[1], [2], [3]])
x.size()

torch.Size([3, 1])

In [13]:
### 차원을 (3,1)에서 (3,4)로 바꾸어라
x.expand(3, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [14]:
### 차원을 (3,1)에서 (-1,4)로 바꾸어라
x.expand(-1, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [16]:
"""repeat : expand 연산은 차원이 1인 어떤 차원의 값을 원하는 사이즈 만큼 같은 값으로 채우는 반면 repeat 연산은 어떤 tensor를 완전히 반복하여 값을 채운다."""
x = torch.rand(2,3)
print(x)
print(x.size())
print()

#  (2, 3) 크기에 (3, 2, 2)로 반복을 하면 (3, 2 X 2, 3 X 2) = (3, 4, 6)이 됨을 알 수 있다.
x.repeat(3,2,2)

tensor([[0.1615, 0.6714, 0.9992],
        [0.7988, 0.9976, 0.2631]])
torch.Size([2, 3])



tensor([[[0.1615, 0.6714, 0.9992, 0.1615, 0.6714, 0.9992],
         [0.7988, 0.9976, 0.2631, 0.7988, 0.9976, 0.2631],
         [0.1615, 0.6714, 0.9992, 0.1615, 0.6714, 0.9992],
         [0.7988, 0.9976, 0.2631, 0.7988, 0.9976, 0.2631]],

        [[0.1615, 0.6714, 0.9992, 0.1615, 0.6714, 0.9992],
         [0.7988, 0.9976, 0.2631, 0.7988, 0.9976, 0.2631],
         [0.1615, 0.6714, 0.9992, 0.1615, 0.6714, 0.9992],
         [0.7988, 0.9976, 0.2631, 0.7988, 0.9976, 0.2631]],

        [[0.1615, 0.6714, 0.9992, 0.1615, 0.6714, 0.9992],
         [0.7988, 0.9976, 0.2631, 0.7988, 0.9976, 0.2631],
         [0.1615, 0.6714, 0.9992, 0.1615, 0.6714, 0.9992],
         [0.7988, 0.9976, 0.2631, 0.7988, 0.9976, 0.2631]]])

In [18]:
"""expand의 경우 원본 tensor를 참조하여 만들기 때문에 원본 tensor가 변경이 되면 expand의 값 또한 변경된다. 
반면 repeat은 깊은 복사로 만들어지기 때문에 원본 tensor가 변경되더라도 값 변경이 발생하지는 않는다."""
a = torch.rand(1, 1, 3)
b = a.expand(4, -1, -1)
c = a.repeat(4, 1, 1)

print(b.shape,'\n\n')
print(c.shape,'\n\n')

a[0, 0, 0] = 0
print(a,'\n\n')

print(b,'\n\n')
print(c)

## 위 코드를 보면 a.expand()를 통해 생성된 b의 값이 원본 tensor인 a의 변경에 따라 같이 변경된 것을 확인할 수 있다.

torch.Size([4, 1, 3]) 


torch.Size([4, 1, 3]) 


tensor([[[0.0000, 0.8984, 0.0991]]]) 


tensor([[[0.0000, 0.8984, 0.0991]],

        [[0.0000, 0.8984, 0.0991]],

        [[0.0000, 0.8984, 0.0991]],

        [[0.0000, 0.8984, 0.0991]]]) 


tensor([[[0.7442, 0.8984, 0.0991]],

        [[0.7442, 0.8984, 0.0991]],

        [[0.7442, 0.8984, 0.0991]],

        [[0.7442, 0.8984, 0.0991]]])
