### Join(cat, stack) 기능 사용 방법
- 파이토치에서 torch.cat(seq, dim)을 이용하여 concaternate 연산을 할 수 있다.
- dim은 concaternate할 방향을 정한다.

In [2]:
import torch

In [3]:
"""torch.cat(seq, dim)"""
x = torch.cuda.FloatTensor([[1,2,3], [4,5,6]])
y = torch.cuda.FloatTensor([[-1,-2,-3], [-4,-5,-6]])
z1 = torch.cat([x,y], dim=0)
print('z1 :', z1, '\n\n')

z2 = torch.cat([x,y], dim=1)
print('z2 :', z2, '\n\n')

z1 : tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]], device='cuda:0') 


z2 : tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]], device='cuda:0') 




In [4]:
"""torch.stack()"""
x = torch.FloatTensor([[1,2,3], [4,5,6]])
x_stack = torch.stack([x,x,x,x], dim=0)
x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

### Slicing 기능 사용 방법
- slicing 기능은 텐서를 몇 개의 부분으로 나눈다.

In [9]:
"""torch.chunk(tensor, chunks, dim=0) // torch.split(tensor, split_size, dim=0)"""

x_1, x_2 = torch.chunk(z1, 2, dim=0)
y_1, y_2, y_3 = torch.chunk(z1, 3, dim=1)
print(z1, '\n\n')
print(x_1)
print(x_2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]], device='cuda:0') 


tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
tensor([[-1., -2., -3.],
        [-4., -5., -6.]], device='cuda:0')


In [11]:
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.],
        [ 4.],
        [-1.],
        [-4.]], device='cuda:0')
tensor([[ 2.],
        [ 5.],
        [-2.],
        [-5.]], device='cuda:0')
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]], device='cuda:0')


### squeezing 기능 사용 방법
- squeeze 함수를 사용하면 차원 중에 1로 되어 있는 것을 압축할 수 있다.
- 차원이 1이면 사실 불필요한 차원일 수 있기에 이럴 때 사용한다.

In [24]:
"""torch.squeeze(input, dim)"""
## dim을 지정하지 않으면 dimension이 1인 모든 차원을 압축하고 dim을 지정하면 지정한 dim만 압축한다.
    # dim=1이라는 소리는 1번째 차원이 아니라 차원의 크기 자체가 1로 되어있는 것을 의미
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [25]:
y = torch.squeeze(x)
print(y.size())

torch.Size([2, 2, 2])


In [26]:
## 0번째 차원이 1이 아니기에 압축되지 않음
y = torch.squeeze(x, 0)
print(y.size())

torch.Size([2, 1, 2, 1, 2])


In [27]:
## 3번째 차원이 1이기에 압축됨
y = torch.squeeze(x, 3)
print(y.size())

torch.Size([2, 1, 2, 2])


In [31]:
"""
torch.unsqueeze()
- unsqueeze 함수를 사용하면 차원을 추가할 수 있다. squeeze와 정확히 반대이다.
- unsqueeze 함수는 차원을 반드시 입력해야 한다.
"""

x = torch.zeros(2,3,4)
print(x.size(), '\n\n')

## 0번째 위치의 차원이 늘어난다.
x = torch.unsqueeze(x, 0)
print(x.size(), '\n\n')

x = torch.unsqueeze(x, 1)
print(x.size(), '\n\n')

torch.Size([2, 3, 4]) 


torch.Size([1, 2, 3, 4]) 


torch.Size([1, 1, 2, 3, 4]) 




### Initialization : 초기화 방법

In [39]:
"""
init.uniform 함수를 사용하면 uniform 또는 normal 분포의 초기화 Tensor를 만들 수 있다.
또는 상수 형태를 바로 만들 수도 있다.
"""
import torch.nn.init as init
x1 = init.uniform_(torch.FloatTensor(3,4), a=0, b=9)
print(x1, '\n\n')

x2 = init.normal_(torch.FloatTensor(3,4), std=0.2)
print(x2, '\n\n')

## 상수 형태의 분포
x3 = init.constant_(torch.FloatTensor(3,4), 3.1415)
print(x3)

tensor([[0.9601, 2.2129, 7.1025, 2.5845],
        [4.6904, 3.7599, 6.3068, 0.1367],
        [6.4853, 3.1847, 0.2838, 5.1375]]) 


tensor([[ 0.1646,  0.2772,  0.2458,  0.0221],
        [ 0.2133, -0.4355,  0.0363,  0.1279],
        [-0.1255, -0.1652,  0.0762, -0.2310]]) 


tensor([[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]])


### Math Operation
- `dot`: vector 내적
- `mv`: 행렬과 벡터의 곱
- `mm`: 행렬과 행렬의 곱
- `matmul`: 인수의 종류에 따라서 자동으로 dot, mm, mv를 선택

In [42]:
"""텐서의 행렬곱: .matmul(), @"""
a = torch.tensor([1,2,3,4,5,6]).view(3,2)
b = torch.tensor([9,8,7,6,5,4]).view(2,3)
ab = torch.matmul(a,b)
ab = a@b # @ 연산자를 이용하여 간단하게 행렬곱을 표현할 수 있음

In [43]:
"""텐서의 산술 연산 방법 -> element wise 연산 방법을 의미
1. torch.add()
2. + 연산자 """
x1 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
x2 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
add = x1 + x2 # add = torch.add(x1,x2) 또한 가능합니다.
print(add)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [45]:
""" +연산자를 이용한 broadcasting 또는 torch.add() with broadcasting"""
x1 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
x1 + 10 # torch.add(x1, 10) 또한 가능합니다.

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [46]:
""" *연산자 또는 torch.mul()"""
x1 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
x2 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
x1*x2 # torch.mul(x1,x2)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [48]:
""" *연산자를 이용한 broadcasting 또는 torch.mul() with broadcasting """
x1 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
x1 * 10
torch.mul(x1, 10)

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [49]:
""" /연산자 또는 torch.div() """
x1 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
x2 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
x1/x2 # torch.div(x1, x2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [51]:
""" /연산자를 이용한 broadcsting 또는 torch.div() with broadcasting """
x1 = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
x1 / 5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

In [53]:
""" power 연산 : torch.pow(input,exponent) """
x1 = torch.FloatTensor([ [1,2,3], 
                        [4,5,6] ])
x1**2 # torch.pow(x1,2)
torch.pow(x1, 2)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [54]:
""" exponential 연산 : torch.exp(tensor,out=None) """
x1 = torch.FloatTensor([ [1,2,3], 
                        [4,5,6] ])
torch.exp(x1)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [55]:
""" torch.log(input, out=None) -> natural logarithm """
x1 = torch.FloatTensor([ [1,2,3], 
                        [4,5,6] ])
torch.log(x1)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

In [56]:
""" torch.mm(mat1, mat2) -> 행렬끼리의 곱셈 """
## Tensor 행렬의 곱을 연산하므로 shape이 잘 맞아야 연산이 가능하다.
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)
torch.mm(x1,x2).size()

torch.Size([3, 5])

In [57]:
""" torch.bmm(batch1, batch2) -> batch 단위의 행렬 곱셈 """
## Tensor(행렬)의 곱을 batch 단위로 처리합니다. torch.mm에서는 단일 Tensor(행렬)로 계산을 한 반면에 batch 단위로 한번에 처리하므로 좀 더 효율적이다.
x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)
torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [58]:
""" torch.dot(tensor1,tensor2)는 두 tensor의 dot product 연산을 수행한다. """
## 각 원소끼리 곱한 뒤에 모두 더함
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)

In [60]:
"""torch.t()를 이용하면 transposed tensor를 구할 수 있다."""
x1 = torch.FloatTensor(2,3)
x2 = x1.t()
print(x1.size())
print(x2.size())

torch.Size([2, 3])
torch.Size([3, 2])


In [61]:
""" torch.transpose()를 이용해서 특정 dimension을 변경할 수 있다. """
x1 = torch.FloatTensor(10,3,4,5)
torch.transpose(x1, 1,2).size()
torch.transpose(x1, 2,3).size()

torch.Size([10, 3, 5, 4])

In [64]:
"""
eigenvalue와 eigenvector를 구하는 방법
출력은 각각 eigenvalue와 eigenvector이다.
"""
x1 = torch.FloatTensor(4,4)
torch.eig(x1,eigenvectors=True)

torch.return_types.eig(
eigenvalues=tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]),
eigenvectors=tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))