# 텐서 
- 텐서는 배열이나 행렬과 매우 유사한 특수한 자료구조입니다. 
- 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 넘파이의 ndarray와 유사합니다. 

In [47]:
import torch
import numpy as np

### 텐서 초기화
- 텐서는 여러가지 방법으로 초기화할 수 있다.

In [48]:
"""데이터로부터 직접 생성하기"""
## 데이터의 자료형은 자동으로 유추
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data.size())
print(x_data)

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [4]:
"""Numpy 배열로부터 생성하기"""
array = np.array(data)
x_np = torch.from_numpy(array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
"""다른 텐서로부터 생성하기"""
## 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(shape)과 자료형(datatype)을 유지한다.
x_ones = torch.ones_like(x_data) # x_data의 shape을 유지
print(f"ones_tensor: \n {x_ones} \n")

# x_data의 자료형은 유지하고, 그 shape을 가지고 random한 수 부여
x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 shape과 자료형 유지
print(f"Random tensor: \n {x_rand} \n")

ones_tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random tensor: 
 tensor([[0.1312, 0.9483],
        [0.4448, 0.4421]]) 



In [11]:
"""무작위 또는 상수 값을 사용하기"""
## shape은 텐서의 차원을 나타내는 튜플로 아래 함수들에서는 출력 텐서의 차원을 결정
shape = (2,3,) # (2,3)이랑 결과가 같음
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"rand_tensor: \n {rand_tensor} \n")
print(f"ones_tensor: \n {ones_tensor} \n")
print(f"zeros_tensor: \n {zeros_tensor} \n")

rand_tensor: 
 tensor([[0.0682, 0.3449, 0.7785],
        [0.8333, 0.5228, 0.9736]]) 

ones_tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros_tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



------

### 텐서의 속성
- 텐서의 속성은 텐서의 shape, datatype 및 어느 device에 저장되는지를 나타낸다.

In [25]:
tensor = torch.rand(3,4)
print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device of tensor : {tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device of tensor : cpu


---------

### 텐서 연산

In [15]:
"""gpu가 존재하면 텐서를 이동"""
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [27]:
"""넘파이 식의 표준 인덱싱과 슬라이싱"""
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First col: {tensor[:, 0]}")
print(f"last col: {tensor[..., -1]}")

## 1번째 열을 모두 0으로 만들기
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First col: tensor([1., 1., 1., 1.])
last col: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
"""텐서 합치기"""
## torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서 연결
## torch.stack도 있음

# 1번째 차원으로 concat하기에 (4,4) -> (4,12)가 됨
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
print(t1.size())

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([12, 4])


In [29]:
## torch.cat과 다르게 stack은 차원 자체가 늘어나게 된다.
t1 = torch.stack([tensor, tensor, tensor], dim=0)
print(t1)
print(t1.size())

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
torch.Size([3, 4, 4])


In [30]:
"""산술 연산"""
print(tensor)
torch.rand_like(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[0.8137, 0.2291, 0.3833, 0.2674],
        [0.6978, 0.6050, 0.2753, 0.3002],
        [0.4532, 0.9711, 0.2018, 0.2027],
        [0.2544, 0.3664, 0.3739, 0.5232]])

In [31]:
"""산술 연산"""
## 두 텐서 간의 행렬 곱
print(tensor)

## 아래의 결과값들은 모두 같다.
y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)

# 변수만 지정하고 연산결과를 해당 변수에 저장
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [32]:
## 요소별 곱을 계산
## 아래의 결과값들은 모두 같다.

z1 = tensor * tensor
z2 = tensor.mul(tensor) # 같은 값을 두 번 곱하면 하나만 써주기

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [34]:
"""단일 요소 텐서: .item()"""
## 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우, item()을 사용하여 python 숫자 값으로 반환할 수 있다.
agg = tensor.sum()
print(agg)
print()

agg_item = agg.item()
print(agg_item,'  ', type(agg_item))

tensor(12.)

12.0    <class 'float'>


In [36]:
"""바꿔치기 연산: 모든 element들에 지정된 수 연산하기"""
## 연산 결과를 피연산자에 저장하는 연산을 바꿔치기 연산이라고 부르며 _접미사를 갖는다.
    # x.copy_(y)나 x.t_()는 x를 변경
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


----

# Numpy 변환
- cpu 상의 텐서와 넘파이 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

In [39]:
"""텐서를 넘파이 배열로 변경하기 : .numpy()"""
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [40]:
### 텐서의 변경 사항이 넘파이 배열에 반영되는 것 확인
t.add_(1)

## 넘파이와 텐서 모두 바뀐 것을 확인
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [41]:
"""넘파이 배열을 텐서로 변경하기 : .from_numpy() """
## 넘파이 및 텐서 지정
n  = np.ones(5)
t = torch.from_numpy(n)

In [46]:
## 넘파이 배열의 변경 사항이 텐서에 반영
np.add(n, 1, out=n) # out으로 출력할 변수명을 적어주거나 새롭게 변수에 할당시키기
print(f"t : {t}")
print(f"n : {n}")

t : tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n : [3. 3. 3. 3. 3.]
